name: Train Churn Model

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "data/**"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data cleaning
        run: python src/data_cleaning.py

      - name: Run feature engineering
        run: python src/feature_engineering.py

      - name: Train model
        run: python src/model_training.py

      - name: Run model evaluation
        run: python src/model_evaluation.py

      - name: Test risk prediction
        run: python src/risk_prediction.py

      - name: Commit trained model
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add models/churn_logistic_regression.joblib
          git commit -m "Update trained churn model" || exit 0
          git push

      - name: Save trained model
        uses: actions/upload-artifact@v4
        with:
          name: churn-model
          path: models/churn_logistic_regression.joblib
